"""empty message

Revision ID: 859860509a3b
Revises: 938759a1df31
Create Date: 2023-04-18 22:52:45.822446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859860509a3b'
down_revision = '938759a1df31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('urls', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('urlvisits', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('urlvisits', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urlvisits', 'updated')
    op.drop_column('urlvisits', 'created')
    op.drop_column('urls', 'updated')
    op.drop_column('urls', 'created')
    # ### end Alembic commands ###
