"""empty message

Revision ID: 938759a1df31
Revises: f09b4f245798
Create Date: 2023-03-21 23:27:52.260507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '938759a1df31'
down_revision = 'f09b4f245798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'short_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('urls', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('urls', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('urls', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('urls', 'short_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
