version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=url_shortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - DB_NAME=url_shortener
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_HOST=postgres
      - SECRET_KEY=super_secret_key
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
