[tool.black]
line-length = 88
skip-string-normalization = true
skip-magic-trailing-comma = true
extend-exclude = '''
(
  \.idea
  | \.(mypy|pytest)_cache
  | migrations
)
'''

[tool.ruff]
extend-exclude=["*/migrations/*"]
