# Generated by Django 3.2.9 on 2021-12-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='unique_id',
            new_name='short_url',
        ),
    ]
