# Generated by Django 3.2.9 on 2021-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_unique_id_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ip_address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
