name: glnk_tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: glnk
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: glnk
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create .env
        run: cp .env.dist .env

      - name: Install dependencies
        run: python -m pip install -r requirements_dev.txt

      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest --cov=app tests
